# Generated by Django 5.1.7 on 2026-08-30 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=128)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('before_summary', models.TextField(blank=True)),
                ('after_summary', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic_case_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ANALYSING', 'Analysing'), ('NEEDS_CLARIFICATION', 'Needs clarification'), ('READY_FOR_MATCHING', 'Ready for matching'), ('AWAITING_ACCEPTANCE', 'Awaiting acceptance'), ('ACCEPTED', 'Accepted'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('workflow_version', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='EMERGENCY', max_length=16)),
                ('referral_reason', models.TextField(blank=True)),
                ('gestational_age_weeks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gravida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('para', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_display_label', models.CharField(default='Synthetic patient', help_text='Synthetic label only — never real identifiers.', max_length=128)),
                ('clinician_confirmed_needs', models.JSONField(blank=True, default=list, help_text='Capability codes confirmed by clinician (not AI-inferred).')),
                ('fully_verified', models.BooleanField(default=False, help_text='True only after findings resolved and clinician approval.')),
                ('incomplete_export_reason', models.TextField(blank=True)),
                ('incomplete_exported_at', models.DateTimeField(blank=True, null=True)),
                ('is_evaluation_case', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('creating_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to='facilities.facility')),
                ('incomplete_exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomplete_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicianApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attestation', models.TextField(default='I confirm I have reviewed the findings and evidence. This approval documents clinician judgment for a synthetic prototype and is not medical clearance for real-world care.')),
                ('workflow_version_at_approval', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinician_approvals', to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_approval', to='referrals.referralcase')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_type', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['observed_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=16)),
                ('clinician_response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_resolutions', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='referrals.referralcase')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=16)),
                ('confirmer_role', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('approval_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_confirmations', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='facilities.facility')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='referrals.referralcase')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MISSING', 'Missing information'), ('CONTRADICTION', 'Contradiction'), ('UNSUPPORTED', 'Unsupported statement'), ('POLICY', 'Policy checklist'), ('SECURITY', 'Security / injection'), ('OTHER', 'Other')], max_length=32)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('INFO', 'Info')], max_length=16)),
                ('message', models.TextField()),
                ('evidence_citations', models.JSONField(default=list, help_text='List of citation objects; empty only if absence is explicit.')),
                ('absence_stated', models.BooleanField(default=False, help_text='True when required information was absent from evidence.')),
                ('resolution_state', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('ACCEPTED_RISK', 'Accepted risk (documented)'), ('WAIVED_INCOMPLETE_EXPORT', 'Shown on incomplete export')], default='OPEN', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('deterministic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='referrals.referralcase')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(max_length=64)),
                ('display_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(max_length=255)),
                ('dose', models.CharField(blank=True, max_length=128)),
                ('route', models.CharField(blank=True, max_length=64)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['administered_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability_coverage', models.JSONField(default=dict)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('availability_freshness', models.CharField(default='unknown', max_length=32)),
                ('explanation', models.TextField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='facilities.facility')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_matches', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('referral', 'facility', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='ReferralDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('structured_content', models.JSONField(default=dict)),
                ('narrative', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('referral', 'version')},
            },
        ),
    ]
