# Generated by Django 5.1.7 on 2026-08-30 18:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_stage', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(default='v1', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('NEEDS_HUMAN', 'Needs human checkpoint')], default='PENDING', max_length=16)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('error_summary', models.TextField(blank=True)),
                ('is_mock', models.BooleanField(default=True)),
                ('is_replay', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTraceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('instruction_summary', models.TextField()),
                ('tool_or_action', models.CharField(max_length=128)),
                ('sanitized_input', models.JSONField(default=dict)),
                ('output_summary', models.TextField(blank=True)),
                ('is_retry', models.BooleanField(default=False)),
                ('human_feedback', models.TextField(blank=True)),
                ('human_checkpoint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_events', to='agents.agentrun')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('run', 'sequence')},
            },
        ),
    ]
