# Generated by Django 5.1.7 on 2026-08-30 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('HEALTH_CENTRE', 'Health centre'), ('DISTRICT_HOSPITAL', 'District hospital'), ('REGIONAL_HOSPITAL', 'Regional hospital'), ('TEACHING_HOSPITAL', 'Teaching hospital')], max_length=32)),
                ('district', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('latitude', models.FloatField(help_text='Synthetic coordinate only')),
                ('longitude', models.FloatField(help_text='Synthetic coordinate only')),
                ('phone_placeholder', models.CharField(default='+233-000-000-000', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fictional', models.BooleanField(default=True, help_text='All seeded facilities are explicitly fictional.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_state', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_links', to='facilities.capability')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_capabilities', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'facility capabilities',
                'unique_together': {('facility', 'capability')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_confirmations', to=settings.AUTH_USER_MODEL)),
                ('facility_capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_updates', to='facilities.facilitycapability')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
