# Generated by Django 5.1.7 on 2026-08-30 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('safe_file_path', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=128)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='referrals.referralcase')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_citation', models.CharField(help_text='Exact source citation required for every fact.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='evidence.evidencedocument')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_facts', to='referrals.referralcase')),
            ],
            options={
                'ordering': ['fact_key', 'created_at'],
            },
        ),
    ]
