FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt /app/backend/requirements.txt
RUN pip install --no-cache-dir -r backend/requirements.txt
COPY . /app
ENV DJANGO_SETTINGS_MODULE=config.settings
WORKDIR /app
